#:schema node_modules/wrangler/config-schema.json
name = "apiv2"
main = "src/index.ts"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
    { binding = "typeauth_keys", id = "9744321d80574d39a97f2b82416e9951", preview_id = "9744321d80574d39a97f2b82416e9951" },
    { binding = "account_keys", id = "9f163d194be040ecb9d742629501b5bf", preview_id = "9f163d194be040ecb9d742629501b5bf" },
    { binding = "app_jwt_keys", id = "abba62c0fb8a4f2f956f71f865f31e2f", preview_id = "abba62c0fb8a4f2f956f71f865f31e2f" },
    { binding = "refill_timestamp", id = "33cec523d07b4711b2f3be0f286ddef6", preview_id = "33cec523d07b4711b2f3be0f286ddef6" },
    { binding = "refresh_token_users", id = "51c6632deee141ed92b3a4840a2d8e90", preview_id = "51c6632deee141ed92b3a4840a2d8e90" },

]

durable_objects.bindings = [
    { name = "RATE_LIMITER", class_name = "RateLimit" },
    { name = "REMAINING", class_name = "Remain" },
]

analytics_engine_datasets = [
    { binding = "ANALYTICS", dataset = "analytics" },
    { binding = "MONITOR", dataset = "monitor" },
    { binding = "AUDIT", dataset = "audit" },

]


[vars]
SENTRY_DSN = "https://f3c43be937456936297fb1c1c8dead1f@o4507042614607872.ingest.us.sentry.io/4507042617425920"
API_TOKEN = "potJ4gvm5u1MyfbkQKxubkN2RlmAULBl5Vr-dhLd"
ACCOUNT_ID = "72b9ea77edd80936fb97de334621368b"
MASTER_API_TOKEN = "kQKxubkN2RlmAULBl5Vr-f9fSNr832rNX"

[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "dev-typeauth-9"
database_id = "598b8b17-03aa-4f34-afda-55757ed1cab5"

[[migrations]]
tag = "v1"
new_classes = ["RateLimit"]

[[migrations]]
tag = "v2"
new_classes = ["Remain"]
